### ISSUE TITLE
Algorytm do ścieżek

### ISSUE THREAD

**Issue by topolskib** [mmazurek/lokalizacja#4]
Przydałoby się napisać algorytm do losowania ścieżek podobny do tego opisanego w ich artykule. W dużym skrócie działa on tak, że wybiera losowo dwa punkty w gmachu, i znajduje najkrótszą ścieżkę między nimi (jeśli są na tym samym piętrze) lub najkrótszą do centralnej klatki schodowej (jeśli są na różnych piętrach). Na tym można by robić dalsze testy modelu

**Comment by mmazurek** [comment]
Zrobiłam algorytm do losowania ścieżek na jednym piętrze. Ograniczyłam długość ścieżki od 5 do 30 "kroków".
